# Generated by Django 4.2.17 on 2024-12-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestatsuser',
            name='avatar',
            field=models.ImageField(default='defaults/default_avatar.png', upload_to='avatar/'),
        ),
    ]
