# Generated by Django 4.2.15 on 2024-10-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournament_tournamentresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatsuser',
            name='avatar',
            field=models.ImageField(default='defaults/default_avatar.jpg', upload_to='avatar/'),
        ),
    ]
