# Generated by Django 4.2.15 on 2024-11-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_gamestatsuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestatsuser',
            name='user',
        ),
        migrations.AddField(
            model_name='gamestatsuser',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
