FROM python:3.9-slim

WORKDIR /app

COPY ./requirements/daphne/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

CMD ["daphne", "-b", "0.0.0.0", "-p", "8003", "gamehub_service.asgi:application"]