global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9113']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'userservice'
    static_configs:
      - targets: ['user-service:8002']

  - job_name: 'gamehubservice'
    static_configs:
      - targets: ['gamehub-service:8003']
